### ISSUE TITLE
Usage with current TYPO3/Fluid versions

### ISSUE THREAD

**Issue by sommerhit76** [NamelessCoder/TYPO3.Fluid.Lint#5]
How can I use this linter with current TYPO3 versions? I don't seem to be able to get it to work with current the Fluid version (^2.5) as Fluid Lint requires Fluid version ^1.0.

**Comment by sommerhit76** [comment]
Oh... I just realised that this linter isn't suitable for Fluid templates within the TYPO3 context (no `f:flashMessages`, no `f:form`).

Are there any plans to enable linting for TYPO3-only view helpers as well?

**Comment by NamelessCoder** [comment]
I think this is only a matter of metadata  since the internals haven't changed in the parts used by this package. You can specify a custom rendering context class name but unfortunately TYPO3 CMS requires a context with things like global configuration, so you'd have to reproduce what goes on in `bin/fluidlint` in, for example, a CommandController.

There are no current plans to extend this since there are more blockers than just the application context which means this package likely will only work for standalone projects.

See however https://github.com/NamelessCoder/typo3-cms-fluid-precompiler-module and companion composer package. When compiling templates, linting is automatically performed - and you gain first-hit performance improvements.

**Comment by lolli42** [comment]
This project is being archived: It is unmaintained since seven years and nobody seems to step in.
In case we want to implement a general linter to Fluid, it should be added to Fluid directly.
